### PR TITLE
 Increase pictrs mem_limit

### PR DESCRIPTION
**Pull request by pixlguru**
Fixes pictrs crashing / OOM

### CODE REVIEW

**Comment by Nutomic** [comment]
@asonix Can you say whats a good default value for this?

**Comment by pixlguru** [comment]
Pictrs has a mem usage averaged out at about 400MiB, I guess we need some headroom

**Comment by asonix** [comment]
When idling pict-rs doesn't need much ram, but if it calls into imagemagick or ffmpeg ram use spikes for the duration. I think I give mine around 1G, but lower values might be okay

**Review by dessalines — APPROVED** [review]
We can always increase it later if necessary. Thanks for this.

**Pull request merged**
