### PR TITLE
Lemmy AlmaLinux/RHEL Ansible Support

### PR DESCRIPTION
**Pull request by codyro**
## Summary

When I initially started working on this #88 didn't exist; however, the scope and approach I took may look more appealing to the maintainers. Sorry @christopher-conley for the duplicated effort--perhaps we can collaborate :).

Please consider this PR, as it would be a boon to the fediverse and the Lemmy project to allow more users to run Lemmy on a more diverse array of systems frictionlessly. There appears to be interest in supporting RHEL based distributions as noted in #81, #88.

This PR should merge cleanly with `HEAD`/pass Woodpecker CI checks (fingers crossed).

I am available on Libera.chat at @CodyRobertson, @codyro:matrix.org on Matrix, or e-mail at cody@almalinux.org if you'd like to chat more or explore other options!

Fresh Lemmy instance setup via this playbook on AlmaLinux 9.2 (latest): https://foss.ly/

## Proposal

I've created a separate `lemmy-almalinux.yml` playbook which I am willing to support and maintain indefinitely. All functionality would mimick the primary `lemmy.yml` playbook and documentation. 

I have targeted AlmaLinux 9, however this should run safely on all RHEL 9 ABI compatible distributions such as CentOS and Rocky Linux. 

## Notable Changes

While there aren't any large changes, there are a few worth noting.

### uninstall.yml

Added blocks with conditionals to uninstall cleanly on Ubuntu & EL9 ([here](https://github.com/codyro/lemmy-ansible/blob/almalinux-support/uninstall.yml#L30-L87))

Added additional prompts and logic to stop/disable `nginx` and `docker`/`podman`.

### podman

In lieu of `docker`, we use `podman` as our container engine in RHEL (usually). For all intents and purposes `podman` can mimick `docker` & `docker-compose` functionality. No changes are necessary for this to work.

### docker-compose.yml

If multiple registries are configured to be searched when pulling an image, it asks the user which one to use. This breaks the unattended install with `ansible`. 

To resolve this, I've explicitly added the registry where the images are hosted (Docker Hub/`docker.io`) ([example](https://github.com/codyro/lemmy-ansible/blob/almalinux-support/templates/docker-compose.yml#L11])).

### firewalld

If `firewalld` is running, add `http/https` services to the `public` zone.

### woodpecker CI

While adding the syntax check for the playbook, I [accidentally submitted a PR](https://github.com/LemmyNet/lemmy-ansible/pull/144), and woodpecker picked up my changes and started running its jobs/pipelines. I don't think this is intended to run on third party PRs?

Thanks for the consideration and keep up the fantastic work :)!

### CODE REVIEW

**Comment by codyro** [comment]
I had a completely different approach I tossed. It would dynamically include playbooks based on distribution. Something along the lines of:

```
import_tasks: "lemmy_{{  ansible_distribution }}.yml"
```

I opted to make an individual playbook instead, leaving the primary `lemmy.yml` untouched because the comment by one of the lead developers [here](https://github.com/LemmyNet/lemmy-ansible/pull/88#issuecomment-1602274987) where they didn't seem to like the idea of maintaining/supporting the playbook for a distribution they're not comfortable with. 

If you are receptive to merging the above idea, I'll happily get that going and update this PR accordingly :)

**Comment by eslerm** [comment]
That's understandable :D Support multiple distros seems like a they would strengthen one another.

What I really want is an ansible playbook with many roles. There could be a role for just installing docker, and another just for configuring nginx, etc, and each role would support multiple distros. That's a lot to do and would need a separate PR/discussion.

Keeping EL as a separate PR seems okay. Ideally scripts could be merged in the future.

**Comment by Nutomic** [comment]
Sorry but I dont like to add support for any other distros so that maintenance stays easy. Its better to create your own repo for those distros, and make a PR to link it in lemmy-docs.

**Comment by codyro** [comment]
That's a shame, but it's your prerogative. I'd be happy to discuss helping maintain the lemmy-ansible project to alleviate the workload, as in its current state, it leaves a lot to be desired. It isn’t targeting any distributions currently, and the Debian-based suggestions don’t work out of the box unless it’s a specific flavor and version. I can fix this and help others implement similar fixes. The issues also need to be triaged. 

There seems to be a healthy community wanting and willing to improve these. If you're ready, I'd love to discuss to see if we can make something happen to move this small part of Lemmy forward. 

Please reconsider this PR and its intention/goal. I genuinely think it’d be a boon to the project to clean up this subproject, as it’s one of the more frictionless ways people get instances going/explore the project/get onboarded. 

As the maintainers, you mention the work for such a large project with so many moving parts and that it requires the community to help. Consider accepting the help instead of brushing it away at first glance. 

So once again, I’d like to improve this project and target the following distributions while making the playbooks cleaner. I can write them all, support them, and write the CI pipeline accordingly (GH workflows, or Woodpecker, your CI of choice). 

* Debian 10
* Debian 11
* Debian 12
* Ubuntu 22.04 LTS
* AlmaLinux 9/RockyLinux 9/RHEL9

If you’re steadfast in your belief that things should continue as-is, please close this PR. 

Cheers!

**Comment by dessalines** [comment]
@codyro Sry I've been slow to get back to you . I'd 100% be in favor of adding additional playbooks like the one you've added for RHEL. 

@Nutomic 's concern is that we've had a lot of people come and go over the years, and have had to remove lots of install methods, because their creators go missing. But I'd be fine with adding this, if you'd be willing to upkeep it.

**Comment by codyro** [comment]
> @codyro Sry I've been slow to get back to you . I'd 100% be in favor of adding additional playbooks like the one you've added for RHEL.
> 
> @Nutomic 's concern is that we've had a lot of people come and go over the years, and have had to remove lots of install methods, because their creators go missing. But I'd be fine with adding this, if you'd be willing to upkeep it.

Thank you for considering this. I'll be happy to maintain it indefinitely and continue contributing to the Debian/Ubuntu playbook.

I am open to going about this in any way you like--whether that be refactoring so there is a single playbook that installs cleanly on a few targets (EX, Debian, Ubuntu, RHEL) or continuing with this proposal and just keeping it separate (probably easier to maintain/for others to contribute). 

Let me know how you'd like to proceed, and I'll review this PR once more and ensure it's safe to merge (I'll make a PR to help with some CI stuff to ensure no breaking changes leak in like in #148).

Feel free to ping me on libera.chat @codyrobertson or on Matrix @CodyRo :)

**Comment by dessalines** [comment]
For sure, thanks! Would you like to help be a maintainer of this repo? It'd ease the burden on me and nutomic.

**Review by dessalines — APPROVED** [review]

**Comment by codyro** [comment]
> For sure, thanks! Would you like to help be a maintainer of this repo? It'd ease the burden on me and nutomic.

I'd happily help you guys out :)!

**Pull request merged**
