### PR TITLE
Move privilege escalation params into config

### PR DESCRIPTION
**Pull request by Nutomic**
@calbasi Can you confirm that this works for you with `ansible-playbook -i inventory/hosts lemmy.yml`?

### CODE REVIEW

**Comment by calbasi** [comment]
> 

I think so. I have been asked for my password. Here you are the output:

> $ ansible-playbook -i inventory/hosts lemmy.yml
> BECOME password: 
> [WARNING]: Unable to parse
> /media/magatzem/magatzem_joan/tmp/kk/lemmy_patched/lemmy-ansible-config-
> params/inventory/hosts as an inventory source
> [WARNING]: No inventory was parsed, only implicit localhost is available
> [WARNING]: provided hosts list is empty, only localhost is available. Note that
> the implicit localhost does not match 'all'
> 
> PLAY [all] *********************************************************************
> skipping: no hosts matched
> 
> PLAY RECAP *********************************************************************
>

**Comment by Nutomic** [comment]
Good, but as the warnings say, there is something wrong with your inventory file so it wont work.

**Comment by Nutomic** [comment]
Actually this is not so great, it asks for root password even when none is set on the server. So this is very annoying for everyone who connects directly as root, or uses passwordless sudo. I think it would be better to set only `become = True`, and mention `-K` param somewhere in the docs for those who need it.

**Comment by dessalines** [comment]
Ok, I'll do a PR for that.

**Pull request merged**
