### PR TITLE
Update NGINX File to combined log

### PR DESCRIPTION
**Pull request by ncorder**
https://nginx.org/en/docs/http/ngx_http_log_module.html

______________________

Let me know if I am incorrect, but I believe main may have been an improperly syntaxed log format

### CODE REVIEW

**Comment by dessalines** [comment]
What's the point of this / what does it solve?

**Comment by ncorder** [comment]
> What's the point of this / what does it solve?

With the current docker setup the log format does not work. Here, I'll post some information in a minute and relaunch my instance, I should have provided that to begin with.

**Comment by ncorder** [comment]
```
root@lemmy:/home/user/lemmy# sudo systemctl start nginx
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
root@lemmy:/home/user/lemmy# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2021-11-05 20:41:59 CDT; 11s ago
       Docs: man:nginx(8)
    Process: 13750 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
        CPU: 8ms

Nov 05 20:41:59 <domain> systemd[1]: Starting A high performance web server and a reverse proxy server...
Nov 05 20:41:59 <domain> nginx[13750]: nginx: [emerg] unknown log format "main" in /etc/nginx/sites-enabled/lemmy.conf>
Nov 05 20:41:59 <domain> nginx[13750]: nginx: configuration file /etc/nginx/nginx.conf test failed
Nov 05 20:41:59 <domain> systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Nov 05 20:41:59 <domain> systemd[1]: nginx.service: Failed with result 'exit-code'.
Nov 05 20:41:59 <domain> systemd[1]: Failed to start A high performance web server and a reverse proxy server.
root@lemmy:/home/user/lemmy# 
```

I replaced my domain with `<domain>` for privacy reasons, but you get the point.

**Comment by dessalines** [comment]
nginx version?

**Comment by ncorder** [comment]
```
root@lemmy:/home/user/lemmy# nginx -v
nginx version: nginx/1.18.0
root@lemmy:/home/user/lemmy#
```

**Comment by dessalines** [comment]
I spose we can use the default combined, but in that case also remove the log format line above.

**Comment by ncorder** [comment]
@dessalines Would you rather swap change `lemmy_main` to `main` or change where it currently states `main` to state `lemmy_main`.

Setting logs to combined also does not result in any errors for NGINX, yet.

**Comment by dessalines** [comment]
That entire log_format line can be gotten rid of then, since combined already has its own format.

**Comment by ncorder** [comment]
:+1: That works

**Comment by dessalines** [comment]
Looks good, thx!

**Pull request merged**
