### PR TITLE
Error: sudo: password required

### PR DESCRIPTION
**Pull request by calbasi**
This PR addresses issue #15

### CODE REVIEW

**Comment by dessalines** [comment]
Seems good to me, although many setups will just use the root user so won't need this. Thanks!

**Comment by Nutomic** [comment]
I would prefer to specify sudo/become options in ansible.cfg, to keep the command which users have to copy shorter.

Should be something like `become: True` and `become_ask_pass: True`.

**Comment by calbasi** [comment]
I understand your point of view. But we need to do something to avoid headaches to users who usually don't work with Ansible.

**Comment by Nutomic** [comment]
The behavior will be identical whether you set the params via command line (like you did in this PR), or via ansible.cfg. But the latter seems simpler for new users, as they dont have to copy extra parameters.

**Comment by dessalines** [comment]
@Nutomic if you do a pr for that we can merge.

**Pull request merged**
